services:
  mariadb:
    image: mariadb:11.4
    container_name: dev-mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: TEST_SAMPLE_DB
      MARIADB_USER: shop
      MARIADB_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: local-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "9090:8080" # App(8080)와 충돌 방지: Host 9090 -> Container 8080
    depends_on:
      - mariadb
    restart: always

volumes:
  mariadb_data:
