spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:TEST_SAMPLE_DB}
    username: ${DB_USERNAME:shop}
    password: ${DB_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:https://accounts-dev.intelliantech.com}
