CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cart_items_member_book UNIQUE (member_id, book_id),
    CONSTRAINT fk_cart_items_member FOREIGN KEY (member_id) REFERENCES members(id),
    CONSTRAINT fk_cart_items_book FOREIGN KEY (book_id) REFERENCES books(id)
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_reviews_member_book UNIQUE (member_id, book_id),
    CONSTRAINT fk_reviews_member FOREIGN KEY (member_id) REFERENCES members(id),
    CONSTRAINT fk_reviews_book FOREIGN KEY (book_id) REFERENCES books(id)
);

CREATE TABLE wishlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_wishlists_member_book UNIQUE (member_id, book_id),
    CONSTRAINT fk_wishlists_member FOREIGN KEY (member_id) REFERENCES members(id),
    CONSTRAINT fk_wishlists_book FOREIGN KEY (book_id) REFERENCES books(id)
);
